{% set data = load_setup_py_data() %}

package:
  name: atef
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - apischema
    - archapp >=1.1.0
    - bluesky
    - bluesky-widgets
    - bluesky-queueserver
    - happi
    - ipython
    - numpy
    - ophyd
    - pydm
    - pyyaml
    - qtpy
    - pyqt
    - rich
    - typhos
    - typing-extensions  # [py<38]

test:
    imports:
      - atef
    requires:
      - pytest

about:
  home: https://github.com/pcdshub/atef
  license: LicenseRef-BSD-3-Clause-SLAC
  summary: "Python Automated Test Execution Framework"
  doc_url: https://pcdshub.github.io/atef/
  dev_url: https://github.com/pcdshub/atef

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
